#!/usr/bin/env python3
"""Human-reviewed survey additions, kept separate from literal catalogue rows."""
from pathlib import Path
import json
HERE=Path(__file__).resolve().parents[1]
D={'components':[],'anchors':[],'issues':[],'leads':[]}
def comp(key,name,source,page,**kw):
 D['components'].append(dict(key=key,name=name,source=source,page=str(page),**kw))
def group(prefix,source,page,parent,names,subsystem,**kw):
 for name in names.split('|'):
  key=prefix+'_'+name.lower().replace(' ','_').replace('-','_')
  comp(key,name,source,page,parent=parent,subsystem=subsystem,**kw)
def anchor(part,feature,source,page,raw,value=None,unit=None,**kw):
 D['anchors'].append(dict(part=part,feature=feature,source=source,page=str(page),raw=raw,value=value,unit=unit,**kw))
def issue(id,title,locator,details,resolution,status='open',marks=[],category='cross_source',severity='high',source=None):
 D['issues'].append(dict(id=id,title=title,locator=locator,details=details,resolution=resolution,status=status,marks=marks,category=category,severity=severity,source=source))
def lead(id,title,vendor,url,date,verification,priority,benefit,limitations,match):
 D['leads'].append(dict(id=id,title=title,vendor=vendor,url=url,date=date,verification=verification,priority=priority,benefit=benefit,limitations=limitations,match=match))

# Survey roots are systems/assemblies, not additional pieces to add to a BOM.
comp('vehicle','Mark VIII vehicle reference envelope','HB',9,kind='assembly',subsystem='Hull and fittings',variant='PRELIMINARY_1918',readiness='B_DOCUMENTED_FORM',basis='Printed envelope dimensions and Plates 1-2; exact skin and mounting coordinates are not fixed by an envelope',figure='1-2',missing='Calibrated section coordinates, ground datum and production configuration')
for key,name,page,sub in [('hull','Hull structure',35,'Hull and fittings'),('engine','Ordnance Liberty engine installation',45,'Engine and lubrication'),('transmission','Epicyclic transmission',119,'Transmission clutch and controls'),('clutch','Compound clutch',115,'Transmission clutch and controls'),('chain','Final drive chain system',130,'Track and running gear'),('track','Road track and running gear',136,'Track and running gear'),('fuel','Fuel and pressure system',29,'Fuel and pressure'),('cooling','Cooling installation',48,'Cooling and ventilation'),('ventilation','Crew ventilation installation',176,'Cooling and ventilation'),('controls','Driver and transmission controls',146,'Transmission clutch and controls'),('electrical','Starting lighting and ignition installation',160,'Electrical and instruments'),('armament','Armament and ammunition stowage',171,'Armament and stowage')]:
 comp(key,name,'HB',page,parent='vehicle',kind='assembly',subsystem=sub,variant='PRELIMINARY_1918')
comp('production','Rock Island production configuration','JORDAN','27-30',kind='configuration_group',subsystem='Hull and fittings',variant='ROCK_ISLAND_FIRST_100',basis='Production account explicitly differs from preliminary specification')
for key,name,qty,page,sub in [('production_fuel','Production 50-gallon gasoline tank',3,29,'Fuel and pressure'),('production_browning','Browning machine gun installation',5,27,'Armament and stowage'),('production_ballball','Ball and Ball tank carburetor',None,29,'Fuel and pressure'),('production_track','Complete track loop',2,30,'Track and running gear'),('production_governor_cup','Governor ball cup',None,29,'Engine and lubrication'),('production_governor_retainer','Governor ball retainer',None,29,'Engine and lubrication'),('production_reinforced_ring','Reinforced transmission internal gear',None,29,'Transmission clutch and controls'),('production_wood','Fuel tank wood packing strip',None,29,'Fuel and pressure'),('production_felt','Felt covering on fuel-tank packing',None,29,'Fuel and pressure')]:
 comp(key,name,'JORDAN',page,parent='production',quantity=qty,kind='assembly' if key in ['production_browning','production_ballball','production_track'] else 'component',subsystem=sub,variant='ROCK_ISLAND_FIRST_100',readiness='D_INSUFFICIENT' if key in ['production_ballball','production_browning','production_fuel'] else 'B_DOCUMENTED_FORM',missing='Exact model identification, production dimensions and installation interfaces')
comp('production_shoe','Production track shoe/link unit','JORDAN',30,parent='production_track',quantity=78,quantity_scope='per_track_loop',related_marks=['M1264'],subsystem='Track and running gear',variant='ROCK_ISLAND_FIRST_100')

# Aircraft items are explicitly kept in an aircraft configuration. They supply
# form evidence for the tank, not automatic fit or interchangeability.
comp('lib_engine','Liberty aircraft engine reference assembly','LIB',5,kind='assembly',subsystem='Engine and lubrication',variant='AIRCRAFT_LIBERTY',figure='1, 13, 35, 74-76')
libgroups=[
 (12,'Cylinder barrel and head|Water jacket front pressing|Water jacket rear pressing|Cylinder holding-down flange|Cylinder holding-down stud|Cylinder holding-down nut','2-6'),
 (13,'High-compression piston|Low-compression piston|Piston crown|Water exit pipe|Rubber water connection','4-8'),
 (14,'Compression ring|Piston skirt oil groove','7-8'),
 (15,'Gudgeon pin|Gudgeon-pin end cap|Forked connecting rod|Plain connecting rod|Forked rod cap|Split bronze big-end bearing shell|Big-end bearing dowel','8-10'),
 (16,'Small-end bronze bush','9-10'),
 (17,'Crankshaft|Front main bearing halves|Rear main bearing halves|Crankshaft end sealing disc|Crankshaft end sealing cap|Main driving bevel and starting claw|Main bevel securing bolt|Main bevel shim|Main thrust bearing|Castellated thrust nut','11-12, 85-86'),
 (18,'Propeller hub|Propeller-hub key|Propeller-key grub screw|Upper crankcase casting|Lower crankcase casting|Thrust locating washer thick|Thrust locating washer thin','12, 14-17, 77'),
 (20,'Crankcase flange bolt|Main bearing tie stud|External crankcase end bolt','14-17'),
 (21,'Distribution-gear compartment|Crankcase oil trap|Crankcase breather|Engine identification plate','14-17, 87'),
 (23,'Main pressure oil pipe|Front-well scavenging pipe|Vertical bearing supply pipe|Oil pipe closing plug|Front oil-well filter|Oil-filter cover|Oil-filter spring clip|Nose felt oil-retaining washer|Rear drive cover plate|Inlet valve|Exhaust valve|Valve guide','16-18'),
 (24,'Inner valve spring|Outer inlet valve spring|Outer exhaust valve spring|Valve spring upper cap|Valve stem split cone','18, 84'),
 (25,'Right camshaft|Left camshaft|Camshaft driven bevel|Distributor driving hub|Camshaft front bush|Camshaft intermediate bearing halves|Camshaft rear thrust bearing shells|Camshaft bearing securing screw|Camcase|Camcase cover|Camcase support stud','19-21, 81-83'),
 (26,'Left valve rocker|Right valve rocker|Cam follower roller|Valve adjusting bolt|Valve adjusting shim|Valve adjusting nut|Valve adjusting split pin|Upper vertical distribution shaft|Lower vertical distribution shaft|Inclined distribution shaft','21-22'),
 (28,'Cylinder water inlet manifold|Cylinder water outlet manifold|Centrifugal water pump|Water-pump impeller|Water-pump shaft|Water-pump packing gland|Water-pump bearing bush','22-23'),
 (31,'Oil pump unit|Oil pressure pump gears|Oil scavenging pump gears|Oil pump body|Oil-pump cover|Oil pressure relief valve|Oil relief spring','24-30, 33-34'),
 (37,'Camshaft oil supply pipe|Camshaft oil inlet bush|Camshaft oil distributor plug','31-32, 34a'),
 (43,'Zenith 52 D.F. carburettor|Zenith float chamber|Zenith float|Zenith needle valve|Zenith main jet|Zenith compensator jet|Zenith shroud tube|Zenith dipping tube|Zenith throttle|Zenith altitude control cock','36-42'),
 (49,'Claudel-Hobson H.C.7 carburettor|H.C.7 float chamber|H.C.7 needle valve|H.C.7 diffuser|H.C.7 throttle barrel|H.C.7 main jet|H.C.7 pilot jet|H.C.7 slow-running tube|H.C.7 altitude control cock','43-50'),
 (61,'Delco ignition generator|Generator armature|Generator commutator|Generator field winding|Generator carbon brush|Generator brush holder|Generator bearing','51'),
 (64,'Voltage regulator|Regulator resistance|Regulator contact|Regulator magnet|Regulator armature','52'),
 (67,'Ignition switchboard|Ignition switchboard mounting bolt|Switchboard tab washer','53-55'),
 (69,'Willard storage battery|Battery wooden case|Battery hard-rubber cell jar|Battery positive plate group|Battery negative plate group|Battery separator|Battery cover|Battery vent plug|Battery terminal connector','56'),
 (76,'Ignition distributor unit|Contact-breaker baseplate|Main contact-breaker lever|Auxiliary contact breaker|Distributor cam|Early cam spindle drive|Later cam spindle drive|Contact-breaker spring','60-67'),
 (81,'Distributor head|Distributor rotor|High-tension cable terminal|Cable insulating plate|High-tension cable','68-71'),
 (87,'Ignition timing control linkage','72-74'),
 (138,'C.C. synchronizing gear cam box|C.C. synchronizing camshaft|C.C. synchronizing ball bearing|C.C. air pump cylinder|C.C. gear driving hub|C.C. gear cover','97')]
for page,names,fig in libgroups:
 group('lib','LIB',page,'lib_engine',names,'Engine and lubrication',variant='AIRCRAFT_LIBERTY',figure=fig,basis='Named in component description; aircraft applicability retained',kind=None)

# Gun and mount: named manufactured objects and integral features are separate.
comp('gun','Hotchkiss Mk II gun and tank mounting reference','GUN','7-21',kind='assembly',subsystem='Armament and stowage',figure='I-VIII, X',missing='Tank-specific mounting coordinates; full detail dimensions of castings and optical internals')
gungroups=[
 (7,'Tube|Jacket|Recoil band|Locking ring|Recoil band set screw','I'),
 (8,'Breechblock|Breechblock removable face plate|Breechblock plate screw|Breechblock firing-pin bushing|Cartridge retaining catch|Breech crank|Crank stud|Crank roller|Crank handles and hub|Crank hub key|Crank hub set screw|Lengthening lever','II-III'),
 (9,'Crank-handle latch plunger|Crank-handle latch spring|Crank-handle latch bracket|Latch bracket screw|Cocking cam|Firing hammer|Firing-pin housing|Firing pin|Rocking shaft|Cocking toe|Recocking handle|Hammer stirrup|Main spring|Sear|Sear spring|Firing arm|Firing shaft|Firing shaft lever|Firing-arm retaining spring|Firing shaft bracket|Extractor','II-III'),
 (10,'Block-stop screw','II-III'),
 (11,'Drill hook','III'),
 (14,'Pivot plate|Clip ring|Revolving bracket|Adjustable pivot|Housing square pin','V-VI'),
 (15,'Cradle|Inner shield supporting bracket|Trunnion cap|Trunnion cap spring pin|Recoil cylinder front plug|Recoil cylinder plug leather washer|Recoil piston and rod|Recoil rod securing nut|Recoil rod securing pin|Recoil stuffing box|Stuffing-box leather washer|Stuffing-box packing|Stuffing-box gland|Recoil filling plug|Filling-plug leather washer|Counter-recoil spring|Counter-recoil rod|Counter-recoil front head|Counter-recoil rear plate|Counter-recoil rod nut|Counter-recoil nut pin|Counter-recoil cylinder closing plug','V-VI'),
 (16,'Shoulder-piece arm|Shoulder-piece hinged steel bar|Shoulder rubber pad|Shoulder-piece hinge|Shoulder-piece locking sleeve|Shoulder-piece sleeve spring|Guard plate|Trigger|Trigger pin|Trigger operating lever|Firing-gear intermediate pin|Firing-gear final lever|Outer shield|Outer shield stay|Inner shield','V-VIII'),
 (17,'Traversing stop|Holding-down bolt|Telescopic sight|Front telescope holder|Rear telescope holder|Front telescope bracket|Deflection screw|Sight rack|Sight pinion|Rear sight bracket|Front holder cover|Rear holder cover|Acorn open foresight|V-notch open rearsight|Telescope center clip|Telescope clip roller|Forked telescope bracket','VIII'),
 (19,'Clamp screw bush (source: brushes)|Clamp bush grub screw|Clip-ring bolt|Pivot keeper screw|Compression lubricator|Lubricating oil screw','V-VIII'),
 (20,'Elevating clamping screw|Clamping arc|Traversing clamping screw','V-VI'),
 (21,'Transport stowage bracket A|Transport securing bolt|Housing stop bolt','X')]
for page,names,fig in gungroups:
 group('gun','GUN',page,'gun',names,'Armament and stowage',figure=fig,basis='Named physical component in gun handbook; dimensions and tank fit not fully established')
for name,page,fig in [('Breech guideway',8,'II'),('Cradle trunnion',15,'VI'),('Cradle recoil cylinder',15,'VI'),('Cradle spring cylinder',15,'VI'),('Shoulder-arm pistol grip',16,'VII')]:
 comp('gun_feature_'+name.replace(' ','_'),name,'GUN',page,parent='gun',kind='feature',subsystem='Armament and stowage',figure=fig,basis='Integral feature of a named manufactured part; not an extra BOM piece')
comp('gun_spares','Spare parts and accessories for two guns','GUN',12,kind='equipment_set',subsystem='Armament and stowage',variant='SPARES_TOOLS',figure='IV')
for name,qty in [('Rocking shaft',2),('Extractor',2),('Firing hammer complete',2),('Firing pin',4),('Firing-pin housing',4),('Sear spring',2),('Main spring',4),('Firing-arm retaining spring',2),('Oil can',1),('Screwdriver',2),('Hand extractor',2),('Tommy',2),('Sight screwdriver wrench',2),('Packing gland set',2),('Lens cleaning cloth',3),('Sponge brush',2),('Sponge rod',2),('Cleaning brush',1)]:
 comp('gun_spare_'+name.replace(' ','_'),name+' (carried spare/accessory)','GUN',13 if name in ['Sponge rod','Cleaning brush'] else 12,parent='gun_spares',quantity=qty,quantity_scope='spare_set_for_two_guns',subsystem='Armament and stowage',variant='SPARES_TOOLS',figure='IV')
for n,desc in [(136,'sighting gear'),(137,'gland piston rod compression rod and clip ring'),(138,'cylinder cap and stuffing box'),(139,'compression rod and plate'),(140,'compression rod and shoulder piece'),(141,'guard and firing gear'),(142,'shield stays'),(143,'piston rod and pivot'),(144,'steel T-handled screwdriver')]:
 comp('gun_tool_'+str(n),'Tool No. '+str(n)+', '+desc,'GUN',21,parent='gun_spares',subsystem='Armament and stowage',variant='SPARES_TOOLS',readiness='D_INSUFFICIENT')

comp('patent_sponson','Alden patent sponson embodiment','PATENT','specification 1-2',kind='assembly',subsystem='Hull and fittings',variant='PATENT_EMBODIMENT',figure='1-3',callout='1',basis='Functional design intent; no dimensional equivalence with production assumed')
for call,name,page,k in [('2','Sponson hinge',1,'component'),('3','Tank wall/frame at sponson',1,'component'),('4','Sponson trailing-edge closure angle',1,'component'),('5','Wall strengthening angle',1,'component'),('6','Sponson securing screw',1,'component'),('7','Sponson roof lip',1,'feature'),('8','Roof closure angle',1,'component'),('9','Sponson hinge-side closure angle',2,'component'),('10','Wall hinge-side closure angle',2,'component'),('13','Shell storage chamber',2,'component'),('14','Shell chamber lightening perforation',2,'feature')]:
 comp('patent_'+call,name,'PATENT','specification '+str(page),parent='patent_sponson',kind=k,subsystem='Hull and fittings',variant='PATENT_EMBODIMENT',figure='1-3',callout=call)

# Explicit anchors: these are specific scalar facts, not complete engineering drawings.
for feature,raw,val in [('overall_length','34 feet 2½ inches',410.5),('overall_width','12 feet',144),('width_sponsons_withdrawn','9 feet',108),('overall_height','10 feet 3 inches',123),('ground_clearance_under_hull','1 foot 8¾ inches',20.75),('track_shoe_width','2 feet 2½ inches',26.5),('track_center_spacing','5 feet 9½ inches',69.5),('ground_contact_length','9 feet 3½ inches',111.5),('expanded_track_length','72 feet 6 inches',870)]:
 anchor('vehicle',feature,'HB',9,raw,val,'in')
for feature,raw,val,unit in [('side_plate_thickness','12 mm',12,'mm'),('rear_fuel_compartment_backplate_thickness','16 mm',16,'mm'),('front_wing_plate_thickness','10 mm',10,'mm'),('main_turret_side_thickness','16 mm',16,'mm'),('main_turret_roof_thickness','6 mm',6,'mm'),('sponson_side_thickness','12 mm',12,'mm'),('sponson_roof_thickness','6 mm',6,'mm'),('sponson_shield_thickness','8 mm',8,'mm'),('door_thickness','12 mm',12,'mm'),('main_turret_length','10 feet 3½ inches',123.5,'in'),('main_turret_width','3 feet 4½ inches',40.5,'in'),('main_turret_height_without_outlook','1 foot 10½ inches',22.5,'in'),('drivers_turret_length','2 feet 3 inches',27,'in'),('drivers_turret_width','1 foot 7 inches',19,'in'),('drivers_turret_height','1 foot 1 inch',13,'in'),('outlook_turret_height_above_main','12½ inches',12.5,'in')]:
 anchor('hull',feature,'HB',35,raw,val,unit)
for feature,raw,val in [('cylinder_bore','5 inches',5),('piston_stroke','7 inches',7),('piston_pin_diameter','1.25 inches',1.25),('piston_pin_length','4 15/16 inches',4.9375),('connecting_rod_center_distance','12 inches',12),('crankshaft_nominal_diameter','2.625 inches',2.625)]:anchor('engine',feature,'HB',45,raw,val,'in')
anchor('lib_engine','cylinder_bank_included_angle','LIB',5,'45°',45,'deg')
anchor('lib_engine','front_main_bearing_length','LIB',17,'115 mm',115,'mm')
anchor('lib_engine','rear_main_bearing_length','LIB',17,'49 mm',49,'mm')
for feature,raw,val in [('chain_pitch','three inch pitch (prose)',3),('chain_inside_width','1 9/16 inches',1.5625),('chain_max_width','4 9/16 inches',4.5625),('chain_roller_diameter','2 inches',2),('roller_pinion_sprocket_diameter','23.031 inches',23.031),('track_driving_wheel_outer_diameter','39.237 inches',39.237),('track_driving_wheel_inner_diameter','32.75 inches',32.75)]:anchor('chain',feature,'HB',130,raw,val,'in')
anchor('chain','chain_links_per_loop','HB',130,'50 pitches',50,'count')
anchor('chain','transmission_drive_sprocket_teeth','HB',130,'12',12,'count')
anchor('chain','driven_chain_sprocket_teeth','HB',130,'23',23,'count')
anchor('chain','road_track_driving_wheel_teeth','HB',130,'35',35,'count')
anchor('track','idler_wheel_diameter','HB',136,'40.187 inches',40.187,'in',basis='Table says track adjusting steel; identify with adjusting/idler wheel using adjoining prose')
anchor('track','mislabelled_driving_wheel_diameter','HB',136,'23.031 (no printed unit)',None,None,status='disputed_direct_dimension',basis='Value belongs to chain sprocket on pp. 130,132; do not use as road-track wheel diameter')
anchor('track','lower_rollers_total','HB',136,'58',58,'count')
anchor('track','lower_rollers_with_springs','HB',136,'28',28,'count')
anchor('track','lower_rollers_without_springs','HB',136,'30',30,'count')
anchor('track','upper_rollers_total','HB',136,'two',2,'count')
anchor('production_track','shoes_per_track','JORDAN',30,'78 shoes each',78,'count')
anchor('production','total_track_shoes','JORDAN',30,'2 tracks × 78 shoes',156,'count',status='derived_dimension',basis='Arithmetic from explicit two loops and per-loop count; excludes spares')
anchor('fuel','preliminary_tank_capacity','HB',29,'80 gallons per tank',80,'gallon_unspecified',basis='Retain source gallon convention; do not convert capacity to physical dimensions')
anchor('production_fuel','production_tank_capacity','JORDAN',29,'50-gallon petrol tanks',50,'gallon_unspecified')
anchor('gun','gun_overall_length','GUN',7,'60 inches',60,'in')
anchor('gun','gun_caliber','GUN',7,'2.244 inches',2.244,'in')
anchor('gun','mount_base_to_bore_center_mean_height','GUN',21,'17.5 inches',17.5,'in')
anchor('gun','telescope_overall_length','GUN',17,'32 inches',32,'in')

issue('SURVEY_01','Fuel capacity and tank shape are configuration-dependent','HB pp. 9,29,33; Jordan pp. 27,29','Preliminary: 3 × 80 gallons, total 240. Production account: 3 × 50 gallons, total 150. Capacity alone does not fix shell geometry.','Keep distinct preliminary and production fuel assemblies. For Rock Island blockout use production capacity as a constraint, not a scale factor applied to the preliminary tank drawing.','variant_separation')
issue('SURVEY_02','Machine guns and stowage cannot be merged across configurations','HB pp. 9,171,175,180,182; Jordan p. 27; SNL pp. 223-225','HB gives seven Hotchkiss machine guns with inconsistent enumerated positions; Jordan gives five Brownings. Ammunition totals also differ. SNL names Browning platform ammunition storage.','Select armament by configuration. Preserve all alternatives and use production photographs/installation drawings before placing ball mounts.','variant_separation')
issue('SURVEY_03','Carburetor change runs in both directions over time','Jordan pp. 29,32; SNL p. 57 and note (gx), p. 309; LIB pp. 43-60','Jordan describes replacing Zenith with Ball & Ball during production; SNL orders Zenith substitution under O.C.M. 2344, 1 September 1922. The aircraft manual also has Claudel-Hobson H.C.7.','Use Ball & Ball for a supported production representation and modified U.S. No. 52 Zenith for a later service alternative. Do not assume H.C.7 was installed in the tank.','resolved_chronology')
issue('SURVEY_04','Electrical counts and voltages in Jordan conflict with technical catalog','Jordan p. 29; HB pp. 160-170; SNL pp. 14,100,123','Jordan lists one 12-V ignition generator, two 6-V generators, two 12-V batteries and one 6-V battery. SNL lists one 8-V Delco generator, one 12-V Bijur generator, a Bijur starting motor, SYR-13 ignition battery and two STR-4 starting/lighting batteries.','Do not build a circuit or physical equipment count from Jordan alone. Use HB wiring and SNL for a dated technical fit; leave historical origin of Jordan wording unresolved.')
issue('SURVEY_05','Lower crankcase bearing counts appear reversed in one assembly','SNL p. 17 versus p. 58; LIB p. 17','SNL individual entries give LQ238A long lower bearing quantity 1 and LQ240A short quantity 6; p. 58 composed-of list gives six LQ238A long and one LQ240A short. Upper halves on p. 59 and LIB front/rear bearing description support one long and six short.','High-confidence proposed correction to the p. 58 association: one long and six short. Raw source edges retained; do not silently edit them.','proposed_high_confidence',marks=['LQ238A','LQ240A','LQ239A','LQ241A'],category='quantity',source='SNL')
issue('SURVEY_06','Road-track wheel and chain sprocket diameter must be separated','HB pp. 130,132,136','The 23.031 value on p. 136 conflicts with the road-track wheel dimensions on p. 130 and matches its chain-sprocket diameter.','Use 39.237-inch outside / 32.75-inch inside for the road-track wheel as printed on p. 130; reserve 23.031 inches for the chain sprocket. p. 136 remains an apparent label error.','proposed_high_confidence',marks=['M1401','M1404','M1540'],category='dimension',source='HB')
issue('SURVEY_07','Pistons differ between aircraft, original tank and replacement','LIB pp. 13-16,109; HB p. 203; SNL pp. 146,165,309-310','Aircraft domed/flat pistons, LQ466A original tank piston and SH1020A replacement must not become one shape. LQ469A ring position is contradictory.','Retain three configuration contexts and unresolved ring location. Tank crown/compression geometry needs exact drawing.','variant_separation',marks=['LQ466A','SH1020A','LQ469A'])
issue('SURVEY_08','Exact manufacturing piece census is unavailable from the catalog alone','SNL note (b), p. 308; note (gy), p. 310; note (gam), p. 310','Some commercial subassembly internals are explicitly omitted; certain supplier products are listed only as units; the spare/accessory addendum is announced for Changes No. 1.','Survey covers all preserved table rows and named supplemental objects. Unlisted internals remain scope gaps, never a claim of zero parts.','documented_limit',category='coverage',source='SNL')
issue('SURVEY_09','Roller total is not 58 plus 28','HB p. 136; SNL p. 197 and note (gp), p. 309','There are 58 lower rollers total, with 28 spring-equipped and 30 plain in HB. SNL note (gp) explains 58 total and 28 when assembled with flange.','58 is the inclusive lower-roller total. Do not sum nested SNL assembly quantities. Upper rollers are a separate pair.','resolved_scope',category='quantity')
issue('SURVEY_10','Sponson stowage requires gun/mount reconfiguration','Alden specification pp. 1-2, Figs. 1-3; GUN p. 21, Plate X; HB Plate 130','Patent shows sponson pivoting inward; gun manual describes a distinct transport arrangement with bracket A, altered gun position and coordinated traverse.','A rigid deployed gun attached to a simply rotating sponson is not a validated stowage animation. Model the transport state and test swept clearance after calibration.','documented_constraint',category='kinematic')
issue('SURVEY_11','Power and reverse-speed summaries disagree','HB p. 9, Plates 74-77; Jordan p. 27','HB gives 338 hp at 1400 rpm and two reverse speeds. Jordan says approximately 400 hp at 1400 rpm and one reverse speed; HB plates illustrate high/low reverse.','Use explicit transmission mechanism evidence for kinematic blockout; retain reported ratings as source claims. Do not infer dimensional changes from the power values.','open',category='specification')
issue('SURVEY_12','Plate scale is not a reliable engineering scale without calibration','HB general arrangement and dimensional plates; SNL restored plates','Restored, dewarped and resized figures have no new measurement authority. SNL Plate 2 aspect ratio remains uncertain.','Retain original-to-derivative transforms, calibrate independent axes with printed dimensions and record residuals before accepting traced coordinates.','documented_limit',category='geometry')
issue('SURVEY_13','Belleville spring dimensional record is physically inconsistent','SNL pp. 138,219; note (gh), p. 309','SH642B outside diameter is smaller than its inside diameter on p. 219; both thickness readings are suspect. Note (gh) permits one Thrackray washer in place of three springs but supplies no correction.','No numerical correction adopted. Seek drawing or measure surviving assembly.','open',marks=['SH642B'],category='dimension',source='SNL')
issue('SURVEY_14','Drawing references with suffix letters are not part marks','SNL pp. 116,144,165','213A accompanies M772; 679A accompanies M280, M270, M285 and M273. A leading-numeric Ordnance reference cannot become the canonical part key.','Use the British piece mark for those identities; retain drawing reference separately. This is a schema/extraction rule, not source errata.','resolved_schema',marks=['M772','M280','M270','M285','M273'],category='identity',source='SNL')
issue('SURVEY_15','Gauge counts and ration boxes include unrealized future-production alternatives','SNL notes (gt),(gv), p. 309','First 100 tanks use four pressure gauges versus three specified for future production; box provision likewise changes.','Future production is a stated alternative, not evidence that a second production batch existed.','variant_separation',category='configuration',source='SNL')

lead('R01','Progress Report of the National Screw Thread Commission','U.S. Bureau of Standards','https://www.govinfo.gov/content/pkg/GOVPUB-C13-ad6e50706050b71202040ad8fadfe95c/pdf/GOVPUB-C13-ad6e50706050b71202040ad8fadfe95c.pdf','1921; approved 19 June 1920','Digitized primary-source PDF opened; title/approval verified',1,'Period thread-series and dimensional reference for generic hardware reconstruction','Postdates initial design; match source U.S. Std./SAE/pipe/USF designation rather than apply indiscriminately',['bolt','screw','nut','stud','thread'])
lead('R02','Report of the National Screw Thread Commission, revised 1924, MP 61','U.S. Bureau of Standards','https://nvlpubs.nist.gov/nistpubs/Legacy/MP/nbsmiscellaneouspub61.pdf','1925','Digitized primary-source PDF opened; title and preface verified',1,'Hardware standards, pipe threads, wood screws and stated revisions from 1921','Revised fit classes and later specifications; useful comparison for 1928 catalog, not proof of original 1918 geometry',['bolt','screw','nut','stud','thread'])
lead('R03','Illustrated catalogue and price list','Lunkenheimer','https://catalog.hathitrust.org/Record/100164840','1908','Catalog record opened; 564 pages, institutional full-view link; item pages not inspected',2,'Candidate comparison for SH962H modified 1/8-inch regulating-tank cock','Need actual catalog entry and modification drawing; modern valve products are not substitutes',['Lunkenheimer','SH962H','cock, regulating'])
lead('R04','The Timken reference manual','Timken','https://catalog.hathitrust.org/Record/002023883','1942','Catalog record opened; 192 pages and full-view link verified; bearing table not inspected',2,'Look for historical cone/cup dimensions for 316/312 and 6454/6420','Later than tank; continuity of exact numbers and profiles remains unverified',['Timken','roller bearing cone','roller bearing cup'])
lead('R05','Part 312 single-cup product page','Timken','https://cad.timken.com/item/tapered-roller-bearings---single-cups/tapered-roller-bearings---single-cups---imperial/312','current','Manufacturer page opened; part identity and separate cup/cone construction verified',3,'Current envelope cross-check and possible CAD reference for cup 312','Not period evidence; no historical interchangeability inferred and no dimensions imported',['Timken','roller bearing cup'])
lead('R06','Homer Jackson Dana Catalog and Brochure Collection, Cage 88, Box 2 Folder 10','Willard / Zenith','https://archiveswest.orbiscascade.org/ark:80444/xv60565','1915-1922 material; Willard 1918 pamphlet and Zenith c.1917 pamphlet','Institutional finding aid opened; named items and location verified; pamphlet images not retrieved',2,'Willard battery construction literature; Zenith compound-nozzle explanation','Finding aid is not a digitized catalog. No SYR-13 / STR-4 or modified U.S. 52 dimensional match established',['Willard','battery','Zenith','carburetor'])
lead('R07','Automobile Ignition, Starting, and Lighting, Charles B. Hayward','Bijur / Delco and other makers','https://books.google.com/books/about/Automobile_Ignition_Starting_and_Lightin.html?id=PE8iAQAAMAAJ','1916; other digitized editions listed','Period book metadata/preview opened; title and scope verified',3,'Contemporary electrical construction and illustrations; candidate Bijur comparison','Not a vendor parts catalog; tank-specific Bijur generator, starter and T461 switch match unverified',['Bijur','Delco','starting motor','starting switch'])
lead('R08','Record Group 156: Office of the Chief of Ordnance','U.S. Ordnance / Rock Island / Bridgeport','https://www.archives.gov/research/guide-fed-records/groups/156.html','1915-1941 record series, including 1918-1920','Official archival guide opened; drawing/correspondence series lead',1,'Original Ordnance drawings, 1922 O.C.M. 2344 carburetor decision, production changes and tank installation details','Series-level lead only; no individual engineering sheet recovered',['sponson','hull','tank','transmission','Ball','carburetor','Browning'])
lead('R09','SNL G-13 Changes No. 1; common hardware SNL H-1/H-2/H-5/H-6/H-7 and G-9','U.S. Ordnance','https://github.com/starseeker/MarkVIIILiberty/blob/main/references/1928-03-30_SNL_G13/1928-03-30_SNL_G13_MarkVIII_Liberty.pdf','1928 references; supplement date unverified','Primary-source cross-references in SNL notes pp. 308-311; separate scans not located',1,'Fill spare/accessory omission and identify exact standard Ordnance hardware','Requested document families, not claims of newly found digitized scans',['bolt','screw','nut','washer','chain','pipe','electrical','accessor'])
lead('R10','Ball and Ball tank carburetor drawing or period catalog','Ball and Ball',None,'1919-1920 production','Exact tank-specific digitized source not located in this search',1,'Largest component-document gap for original Rock Island engine appearance and interfaces','Later automotive Ball & Ball/Carter catalogs cannot establish tank shape',['Ball','carburetor'])
lead('R11','Bijur tank generator, starting motor and T461 switch drawings','Bijur',None,'1918-1928','Exact tank-specific digitized catalog not located; SNL note (gy) explains unit-only coverage',1,'Dimensions, end frames, terminals and mounting feet of proprietary equipment','Do not reconstruct internal details from a generic dynamo illustration',['Bijur','starting motor','starting switch'])
lead('R12','Johns-Manville distance recorder M-26 and tachometer; Edelman gauge','Johns-Manville / Edelman',None,'1918-1928','Exact period product manuals not located; SNL pp. 97,162,214,244 give identities',2,'Gauge diameters, cases, mounting patterns, drive threads and cable interfaces','Dimensions and vendor continuity unverified',['Johns','recorder','tachometer','Edelman','oil pressure gage'])
lead('R13','Titeflex/Penflex hose and fitting catalogs; period drive-chain catalogs','Titeflex / Penflex / Diamond / silent-chain makers',None,'1918-1928','Exact relevant digitized editions not located; SNL pp. 2,61-62,73,263 provide starting specifications',2,'End fitting geometry, braid appearance, bend radii, chain form','SNL lengths and threads retained; generic modern hoses/chains are only provisional geometry',['Titeflex','Penflex','Diamond','silent chain','armor flexible'])
lead('R14','Stanley No. 808 hinge and Appleton Unilet catalogs','Stanley / Appleton',None,'1918-1928','Exact period catalog matches not located; SNL p. 106 and pp. 264-265 establish names',2,'Leaf shape, knuckles and hole spacing; conduit-box castings and threaded entries','2½-inch hinge size does not alone establish pattern',['Stanley','808','Unilet','Appleton'])

issue('SURVEY_16','Preliminary engine text imports aircraft details and contains numerical anomalies','HB p. 45 and p. 95; LIB pp. 12,25','HB p. 45 describes cast-iron cylinders and 24 cams on each camshaft, while the aircraft description uses welded steel cylinders and the valve train does not support treating that count as a literal tank shaft specification. HB p. 95 expressly excludes the propeller hub from the Ordnance engine.','Do not copy aircraft attachments or disputed material/cam-count statements into tank CAD. Retain documented tank identifiers and seek tank-specific cylinder and camshaft drawings.','open',category='applicability',source='HB')
issue('SURVEY_17','Advertised handbook insert is not independently identified','HB plate list; preserved reconstruction history; SNL Plate 2','Earlier reconstruction work recorded 143 plates plus an insert, but no separately identified handbook insert. The present survey has 143 handbook index entries and the SNL longitudinal foldout. These are not evidence that the missing handbook insert has been recovered.','Use SNL Plate 2 as a documented longitudinal-section source and keep the handbook insert as an archival search gap.','documented_limit',category='coverage',source='HB')
lead('R15','Mark VIII Tank, Ordnance Notes and Handbooks on Guns and Gun Carriages','U.S. National Archives',None,'Series 1900-August 1941; Rock Island creator','Archive panel transcribed in repository foldout_provenance.json; external item availability not independently checked',1,'Specific series identifier 26417262, container 5, item Mark VIII Tank; stronger starting point for requesting original plates or associated handbook material','Identifier is for the cited archival record/series, not an assertion that every tank drawing is digitized',['hull','sponson','tank','track'])
# Preserve explicit source locations for every reviewed record.
paths={'HB':'references/1925-03-06_Preliminary_Handbook_Mark_VIII_Tank/Handbook_Project/data/front_matter.py','LIB':'references/1918-09_12_Cylinder_Liberty_Aero_Engine/Liberty_Project/data/transcription.json','GUN':'references/1919-08-15_Handbook_QF_Hotchkiss_2.244in_6pdr/Hotchkiss_Project/data/lines.json','JORDAN':'references/1920-07_Manufacture_of_Mark_VIII_Tanks/Article_Project/data/reviewed_transcription.json','PATENT':'references/1921-01-25_US1366550A/US1366550A_Project/data/reviewed_transcription.json'}
for r in D['components']+D['anchors']:
 r['path']=paths[r['source']]
 if r['source']=='HB':
  page=int(r['page']);part=(page-1)//50+1
  r['path']=f'references/1925-03-06_Preliminary_Handbook_Mark_VIII_Tank/Preliminary_Handbook_MarkVIII_Tank_Part_{part}_of_5.pdf'
for r in D['components']:
 if r['name'] in ['Piston crown','Piston skirt oil groove','Distribution-gear compartment','Cylinder holding-down flange']:
  r['kind']='feature';r['basis']='Integral feature, not an additional manufactured piece; aircraft applicability retained'
 if r['key'].startswith('gun_spare_'):
  base=r['name'].removesuffix(' (carried spare/accessory)')
  if base in ['Rocking shaft','Extractor','Firing pin','Firing-pin housing','Sear spring','Main spring','Firing-arm retaining spring']:
   r['same_as']='gun_'+base.lower().replace(' ','_').replace('-','_')
(HERE/'inputs/curated_survey.json').write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
print({k:len(v) for k,v in D.items()})
